abi = [{
    'constant': True,
    'inputs': [],
    'name': "uniswapDapAddress",
    'outputs': [{
        'name': "",
        'type': "address"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "hasClosed",
    'outputs': [{
        'name': "",
        'type': "bool"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "initialized",
    'outputs': [{
        'name': "",
        'type': "bool"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [{
        'name': "",
        'type': "address"
    }],
    'name': "contributors",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "presaleEndTime",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "CheckTotalEthRaised",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "rate",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "cap",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "goal",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "weiRaised",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [{
        'name': "contributor_addr",
        'type': "address"
    }],
    'name': "checkContributorValidity",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': False,
    'inputs': [],
    'name': "claimTokens",
    'outputs': [],
    'payable': False,
    'stateMutability': "non'payable'",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "closingTime",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': False,
    'inputs': [],
    'name': "ReleaseFundsToPlatform",
    'outputs': [],
    'payable': False,
    'stateMutability': "non'payable'",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "capReached",
    'outputs': [{
        'name': "",
        'type': "bool"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "wallet",
    'outputs': [{
        'name': "",
        'type': "address"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "governorContract",
    'outputs': [{
        'name': "",
        'type': "address"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "test_tag",
    'outputs': [{
        'name': "",
        'type': "string"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "finalizeValid",
    'outputs': [{
        'name': "",
        'type': "bool"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': False,
    'inputs': [],
    'name': "renounceOwnership",
    'outputs': [],
    'payable': False,
    'stateMutability': "non'payable'",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "goalReached",
    'outputs': [{
        'name': "",
        'type': "bool"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "claimTokensTestView",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "isFinalized",
    'outputs': [{
        'name': "",
        'type': "bool"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "owner",
    'outputs': [{
        'name': "",
        'type': "address"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': False,
    'inputs': [{
        'name': "uniswapDep",
        'type': "address"
    }, {
        'name': "tokenFee",
        'type': "uint256"
    }],
    'name': "mintForUniswap",
    'outputs': [],
    'payable': False,
    'stateMutability': "non'payable'",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "presaleStartTime",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': False,
    'inputs': [{
        'name': "tokenFee",
        'type': "uint256"
    }, {
        'name': "_platAddrs",
        'type': "address"
    }],
    'name': "mintForPlatform",
    'outputs': [],
    'payable': False,
    'stateMutability': "non'payable'",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "finalizeTimeout",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': False,
    'inputs': [],
    'name': "claimRefund",
    'outputs': [],
    'payable': False,
    'stateMutability': "non'payable'",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "openingTime",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "Preaslefinalized",
    'outputs': [{
        'name': "",
        'type': "bool"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "minEthContribution",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "CheckHardCap",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': False,
    'inputs': [{
        'name': "__finalizeInfo",
        'type': "address[3]"
    }, {
        'name': "validFinalize",
        'type': "bool"
    }],
    'name': "finalize",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "non'payable'",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "maxEthContribution",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "checkRate",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "CheckSoftCap",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [{
        'name': "",
        'type': "address"
    }],
    'name': "contributorsTracker",
    'outputs': [{
        'name': "",
        'type': "uint256"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': False,
    'inputs': [{
        'name': "_beneficiary",
        'type': "address"
    }],
    'name': "buyTokens",
    'outputs': [],
    'payable': True,
    'stateMutability': "'payable'",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "hasEnded",
    'outputs': [{
        'name': "",
        'type': "bool"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "presaleCreator",
    'outputs': [{
        'name': "",
        'type': "address"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': False,
    'inputs': [{
        'name': "_newOwner",
        'type': "address"
    }],
    'name': "transferOwnership",
    'outputs': [],
    'payable': False,
    'stateMutability': "non'payable'",
    'type': "function"
}, {
    'constant': False,
    'inputs': [{
        'name': "tokenAdrs",
        'type': "address"
    }],
    'name': "seeDecimals",
    'outputs': [{
        'name': "",
        'type': "uint8"
    }],
    'payable': False,
    'stateMutability': "non'payable'",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "vault",
    'outputs': [{
        'name': "",
        'type': "address"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'constant': True,
    'inputs': [],
    'name': "token",
    'outputs': [{
        'name': "",
        'type': "address"
    }],
    'payable': False,
    'stateMutability': "view",
    'type': "function"
}, {
    'inputs': [{
        'name': "token",
        'type': "address"
    }, {
        'name': "_rate",
        'type': "uint256"
    }, {
        'name': "start_end_time",
        'type': "uint256[2]"
    }, {
        'name': "targetUserWallet",
        'type': "address"
    }, {
        'name': "soft_hard_cap",
        'type': "uint256[2]"
    }, {
        'name': "_min_max_eth",
        'type': "uint256[2]"
    }, {
        'name': "_govUniPercentage",
        'type': "uint256[2]"
    }],
    'payable': False,
    'stateMutability': "non'payable'",
    'type': "constructor"
}, {
    'payable': True,
    'stateMutability': "'payable'",
    'type': "fallback"
}, {
    'anonymous': False,
    'inputs': [],
    'name': "Initialized",
    'type': "event"
}, {
    'anonymous': False,
    'inputs': [{
        'indexed': False,
        'name': "startTime",
        'type': "uint256"
    }, {
        'indexed': False,
        'name': "endTime",
        'type': "uint256"
    }, {
        'indexed': False,
        'name': "oldStartTime",
        'type': "uint256"
    }, {
        'indexed': False,
        'name': "oldEndTime",
        'type': "uint256"
    }],
    'name': "TimesChanged",
    'type': "event"
}, {
    'anonymous': False,
    'inputs': [],
    'name': "Finalized",
    'type': "event"
}, {
    'anonymous': False,
    'inputs': [{
        'indexed': True,
        'name': "previousOwner",
        'type': "address"
    }],
    'name': "OwnershipRenounced",
    'type': "event"
}, {
    'anonymous': False,
    'inputs': [{
        'indexed': True,
        'name': "previousOwner",
        'type': "address"
    }, {
        'indexed': True,
        'name': "newOwner",
        'type': "address"
    }],
    'name': "OwnershipTransferred",
    'type': "event"
}, {
    'anonymous': False,
    'inputs': [{
        'indexed': True,
        'name': "purchaser",
        'type': "address"
    }, {
        'indexed': True,
        'name': "beneficiary",
        'type': "address"
    }, {
        'indexed': False,
        'name': "value",
        'type': "uint256"
    }, {
        'indexed': False,
        'name': "amount",
        'type': "uint256"
    }],
    'name': "TokenPurchase",
    'type': "event"
}]
  